language: php

services:
  - docker

before_script:
  - docker-compose -f docker-compose-test.yml up --build -d

script:
   - docker exec symfony-docker-php composer install
   - docker exec symfony-docker-php ls
   - docker exec symfony-docker-php sh -c "cd /var/cache/test && ls"
   #- docker exec symfony-docker-php sh -c "rm test
   - docker exec symfony-docker-php ./bin/console doctrine:fixtures:load --no-interaction --env=test
   - docker exec symfony-docker-php ./bin/phpunit --no-coverage --colors=always