language: php

services:
  - docker

before_script:
  - docker-compose -f docker-compose-test.yml up --build -d

script:
   - docker exec symfony-docker-php composer install
   - docker exec symfony-docker-php php bin/console doctrine:database:create --env=test
   - docker exec symfony-docker-php php bin/console doctrine:schema:update --env=test --force
   - docker exec symfony-docker-php ./bin/console doctrine:fixtures:load --no-interaction --env=test
   - docker exec symfony-docker-php ./bin/phpunit --no-coverage --colors=always