language: php

services:
  - docker

before_script:
  - ls -a
  - docker-compose -f docker-compose-test.yml up --build -d

script:
  - ls -a
  - docker ps
  - docker exec -ti symfony-docker-php bash -c "php bin/console doctrine:fixtures:load --no-interaction && bin/phpunit --no-coverage --colors=always --stderr"