language: php

services:
  - docker

before_script:
  - docker-compose -f docker-compose-test.yml up --build -d

script:
   - docker exec -ti symfony-docker-php /bin/sh -c "php bin/console doctrine:fixtures:load --no-interaction && bin/phpunit --no-coverage --colors=always --stderr"