language: php

services:
  - docker

before_script:
  - docker-compose -f docker-compose-test.yml up --build --no-cache -d

script:
  - docker ps
  - docker exec -ti symfony-docker-php bash
  - php bin/console doctrine:fixtures:load --no-interaction
  - bin/phpunit --no-coverage --colors=always --stderr