version: '3.3'

services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    image: nginx:latest
    env_file:
      - .env.test
    expose:
      - ${WEB_CONTAINER_PORT}
    ports:
      - ${WEB_MACHINE_PORT}:${WEB_CONTAINER_PORT}
      - ${WEB_MACHINE_SSL_PORT}:${WEB_CONTAINER_SSL_PORT}
    volumes:
      - ./:/app
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - agence

  php:
    container_name: ${APP_CONTAINER_NAME}
    build: ./.docker/php-fpm
    restart: on-failure
    env_file:
      - .env.test
    expose:
      - ${APP_UPSTREAM_PORT}
    volumes:
      - .:/app
    depends_on:
      - sqlite
    networks:
      - agence

  sqlite:
    container_name: sqlite
    build: .docker/sqlite
    restart: on-failure
    env_file:
      - .env.test
    volumes:
      - ./var/cache/test:/var/cache/test
    networks:
      - agence

  redis:
    container_name: ${CACHE_CONTAINER_NAME}
    build: ./.docker/redis
    restart: always
    expose:
      - ${CACHE_PORT}
    ports:
      - ${CACHE_MACHINE_PORT}:${CACHE_PORT}
    volumes:
      - ./${CACHE_VOLUME}:/var/lib/redis:rw
    sysctls:
      net.core.somaxconn: 65535
    networks:
      - agence

  maildev:
    image: djfarrelly/maildev
    ports:
      - ${MAIL_DEV_MACHINE_PORT}:${MAIL_DEV_CONTAINER_PORT}
    networks:
      - agence

networks:
  agence: